// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cars": {
            "get": {
                "description": "Returns cars",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Get cars",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Price from to filter",
                        "name": "price_from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Price to to filter",
                        "name": "price_to",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Cars",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.CarsGetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cars not found",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates new car",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Create car",
                "parameters": [
                    {
                        "description": "Car",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.CarCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Car",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.CarCreateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/cars/{id}": {
            "get": {
                "description": "Returns car by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Get car by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Car ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Car",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.CarGetByIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cars not found",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes car by its ID",
                "tags": [
                    "Cars"
                ],
                "summary": "Delete car",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Car ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Car"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cars not found",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Updates car by its ID",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Cars"
                ],
                "summary": "Update car",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Car ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Car",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.CarUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Car"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Cars not found",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/carshop_internal_domain.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "carshop_internal_domain.Car": {
            "type": "object",
            "properties": {
                "build_date": {
                    "type": "string"
                },
                "colour": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "carshop_internal_domain.CarCreateRequest": {
            "type": "object",
            "properties": {
                "build_date": {
                    "type": "string"
                },
                "colour": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "carshop_internal_domain.CarCreateResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "carshop_internal_domain.CarGetByIDResponse": {
            "type": "object",
            "properties": {
                "car": {
                    "$ref": "#/definitions/carshop_internal_domain.Car"
                }
            }
        },
        "carshop_internal_domain.CarUpdateRequest": {
            "type": "object",
            "properties": {
                "build_date": {
                    "type": "string"
                },
                "colour": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "carshop_internal_domain.CarsGetResponse": {
            "type": "object",
            "properties": {
                "cars": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/carshop_internal_domain.Car"
                    }
                },
                "next_cursor": {
                    "type": "integer"
                }
            }
        },
        "carshop_internal_domain.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Akademia API Gateway",
	Description:      "API Gateway для системы Akademia",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
